### ISSUE TITLE
[1.20.1] A mod is trying to add an entity from offthread SPAM IN CONSOLE

### ISSUE THREAD

**Issue by Camawama** [SrRapero720/dimthreads#10]
I am working on a large modpack and thought that this mod could really help server performance. After testing it out, it does seem to help performance...but there is constant log spam almost everytime something happens.

A mod is trying to add an entity from offthread, this should be avoided. Printing trace:
java.lang.Exception: null

Have fun scrolling, I'm sorry.

[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/14681705/latest.log)

**Comment by Camawama** [comment]
Don't know if this will help but I ran spark. https://spark.lucko.me/3kjGhrR9X9
 I made sure to run it with this command _/spark profiler --thread *_

**Comment by SrRapero720** [comment]
consider update dimtreads to latest version, you're using 1.0.0 and cupboard issues are fixed in latest

**Comment by Camawama** [comment]
My bad, I didn't notice since it's not showing the new version on Modrinth.
![image](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/43620900/e4318b16-94e6-43c8-8f99-0e8613494033)

**Comment by Camawama** [comment]
Also, seems to be working fine after the update. Thank you!
