### ISSUE TITLE
Incompatibility with Arclight Server

### ISSUE THREAD

**Issue by etncc** [SrRapero720/dimthreads#12]
Arclight server which is a custom server jar that runs forge with bukkit plugin support. But unfortunately when running this mod on a fresh server it crashes. Almost every mod I used works with it so it would be nice if with mod could work.
Link to the github of Arclight: https://github.com/IzzelAliz/Arclight

**Comment by SrRapero720** [comment]
do... not... expect support on my side for arclight, or by any other performance mod. content mods are very sensitive to performance mods and dimthreads is not the exception. plugins are more complicated to debug and some plugins do weird things on dimensions which i am very sure will not work with the mod.

sorry but not support on my side for hybrid servers (unless the author of the mod states something else)
