### ISSUE TITLE
[CRASH] Forge 1.20.1

### ISSUE THREAD

**Issue by Camawama** [SrRapero720/dimthreads#13]
While running a server with DimensionalThreading and using Chunky to pre-generate chunks, the server crashed. 

MC: 1.20.1
FORGE: 47.2.17
DIM THREADS: 1.0.4

LOGS:
[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/14913967/latest.log)

CRASH REPORT:
[crash-2024-04-09_05.56.18-server.txt](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/14913969/crash-2024-04-09_05.56.18-server.txt)

**Comment by Camawama** [comment]
This also happened while I was not running spark and I had the thread count set to 20 on a 24 thread CPU

**Comment by Camawama** [comment]
removed dimthreads and it seemed to fix the issue but it randomly started happening again without. Not your mod.

**Comment by SrRapero720** [comment]
why i didn't get notifications from this repo aaaaaaaaaaaaaaaaaaa
