### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rjdxxxxxccc** [SrRapero720/dimthreads#15]
[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/15284937/latest.log)
game exit

**Comment by SrRapero720** [comment]
try upading dimthreads to latest version

**Comment by rjdxxxxxccc** [comment]
[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/15286614/latest.log)

it will still exit the game

**Comment by SrRapero720** [comment]
i didnt checked it properly before
but the crash was not caused by dimensional threading

culprit is between alexcaves, the bumblezone and bosses of mass destruction
