### ISSUE TITLE
Please add a config option for initial thread count

### ISSUE THREAD

**Issue by son0fether** [SrRapero720/dimthreads#16]
Hi there, this mod looks like it would be a great improvement to performance on servers.

However, its default would be too low for modpacks with dimensions, and the instructions say it would make things worse with too few threads.

Could you please add a config file with an entry for the initial value of dimthread_thread_count (default 3 of course)?  This would make it safer to include this mod in modpacks.

I can think of a workaround, which is to add some function in a datapack that sets the gamerule value on some trigger, like players logging in, but it's kind of awkward.

Thank you.

**Comment by SrRapero720** [comment]
i like the idea, i'll look into it
