### ISSUE TITLE
[1.20.1] Dimthread crash with Effortless Building

### ISSUE THREAD

**Issue by Reshy** [SrRapero720/dimthreads#22]
Thread Dump:  https://pastebin.com/v2KCvKzN

Not sure how to make it happen reliably.  Seems like the client/server can lock up if placing enough blocks using effortless building.

**Comment by SrRapero720** [comment]
Seems like C2ME is the culprit because is locking one of the dimthreads thread waiting for other thread.

Try without it, come back if still persist

**Comment by SrRapero720** [comment]
C2ME is not supported, sinitra is not even supported to.
