### ISSUE TITLE
Possible C2ME compat issue

### ISSUE THREAD

**Issue by MrTime4ik** [SrRapero720/dimthreads#23]
Server crushed
[crash-2024-08-13_07.43.28-server.txt](https://github.com/user-attachments/files/16598225/crash-2024-08-13_07.43.28-server.txt)

**Comment by SrRapero720** [comment]
remove c2me and try again.... seems like both mods was colliding (but not sure)
i will investigate, consider also report the crash to the c2me author.

**Comment by SrRapero720** [comment]
i am idiotic enough to not see the big "connector is here". i focused on read the stackctrace.
well, C2ME wasn't properly ported to forge/neoforge. which means i can't provide support for a mod that wasn't designed to work on the proper modloader

forge has important things such as event firing. so c2me has a huge road to even work without struggle other mods.
in short: no compat to sinitra or c2me

**Comment by UnnamedWei** [comment]
Hello just wanna ask if it’s c2me for fabric, would it be compatible?

**Comment by S0apyy** [comment]
> Hello just wanna ask if it’s c2me for fabric, would it be compatible?

yes c2me works with this mod on fabric

**Comment by UnnamedWei** [comment]
Thanks! I will try it out, dose it compat with multiworld also?
