### ISSUE TITLE
Help me! I managed to launch the game server, but it didn't take long for it to crash The version is 1.20.1

### ISSUE THREAD

**Issue by Lonmo0208** [SrRapero720/dimthreads#27]
Help me! /(ㄒoㄒ)/~~ I managed to launch the game server, but it didn't take long for it to crash
The version is 1.20.1
[crash-2024-09-29_02.19.45-server.txt](https://github.com/user-attachments/files/17175868/crash-2024-09-29_02.19.45-server.txt)

**Comment by SrRapero720** [comment]
do not use arclight, and no i am not supporting non-pure forge environments

**Comment by Lonmo0208** [comment]
> 不使用 Arclight，不，我不支持非纯 Forge 环境

QAQ OK~
