### ISSUE TITLE
[Meta] Create list of known incompatible/problematic mods

### ISSUE THREAD

**Issue by Demopans** [SrRapero720/dimthreads#29]
As stated in the title. The mod page already states mods such as AE2 are known to be borked when ran with DimThread. This proposal extends it further by pooling additional information sourced from the community. Ideally, this list should be a pinned issue for quick reference

**Comment by SrRapero720** [comment]
I need to do some research about, Dimtreads supports from 1.16.5 to 1.21.x and a lot of mods changes a lot of things depending of the version (including create mod), and i barely have time

thats why i didn't make yet a proper issue listing all the mods...

**Comment by SrRapero720** [comment]
I made one: #31
here i'm going to put all incompatible mods i found
