### ISSUE TITLE
SpawncapControlUtility incompatibility

### ISSUE THREAD

**Issue by LCJRL** [SrRapero720/dimthreads#4]
请问”游戏中该mod会突然导致生成几千个实体，还不停的生成“的问题修复了吗

**Comment by SrRapero720** [comment]
is still present and is caused by "SpawncapControlUtility" mod.
I will (attempt) to fix it in a near future

**Comment by SrRapero720** [comment]
in a future, please open proper issues in english (or almost in spanish) i doesn't understand any oriental language kanji based

**Comment by LCJRL** [comment]
Okey,thanks

**Comment by SrRapero720** [comment]
after reading the spawncamp code... it can't be the cause. it was just a reflection on startup (even before dimthreads can... run)
i will move this to #5
