### ISSUE TITLE
Possible incompatibility with Critters and Companions mod. (1.19.2)

### ISSUE THREAD

**Issue by MadDifferentMethods** [SrRapero720/dimthreads#7]
[crash-2024-02-11_22.34.24-server.txt](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/14248489/crash-2024-02-11_22.34.24-server.txt)

I'm not an expert but I can read and at the possible causes it mentions this and the aforementioned mod as possible culprits.

**Comment by SrRapero720** [comment]
try without DimensionalThreads, if issue is stil present then is an issue of Critters and Companions

**Comment by MadDifferentMethods** [comment]
will do and i will let you know.

**Comment by MadDifferentMethods** [comment]
ok, the game still crashes without Dimensional Threading, so it has nothing to do with it, im sorry for any inconvenience I may have caused!
