### ISSUE TITLE
What occurs when # of Dimension Exceeds # of threads?

### ISSUE THREAD

**Issue by Neoteric-Dev** [SrRapero720/dimthreads#9]
What occurs when # of Dimension Exceeds # of threads?
Is there any prioritisation, or is it just round-robin multiple dimensions on the same thread?

**Comment by SrRapero720** [comment]
https://github.com/SrRapero720/DimensionalThreading-Reforked?tab=readme-ov-file#can-i-use-dimthread-if-i-have-less-threads-on-my-cpu-than-dimensions
